### ISSUE TITLE
Mod Requires NBTcrafting which isn't updated

### ISSUE THREAD

**Issue by lubcubsgaming** [saperate/SlimePearls#1]
I am trying to use this mod on 1.19.4 fabric and NBT Crafting is only updated to 1.19.2. When I try to launch with 1.19.2 nbt crafting, it just crashes.

**Comment by saperate** [comment]
Hey there!

I'm really happy that you want to try out my mod, though it would seem that you are right about the fact that NBT Crafting is not compatible with 1.19.4. For now, i will label my mod as only compatible with 1.19-1.19.2, I will push out a fix for that as soon as possible. Anyway, thank you for bringing this to my attention and have a great day!

**Comment by saperate** [comment]
Seems like the problem is bigger than i thought, i might have to remake the mod from scratch to be able to fix this. I'll keep this issue updated on my progress

**Comment by saperate** [comment]
I've just finished remaking the mod for 1.19.4, it does not need NBT Crafting anymore, i'll test it out on different versions to see which one is compatible, but i'll mark this issue as closed. @lubcubsgaming , i've uploaded it to the modrinth page, it just needs to be approved by mods, so keep an eye out for that. Happy gaming!
